language: csharp
mono: none
sudo: required
dotnet: 3.1
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
script:
  - dotnet restore
  - dotnet test ./Rijndael256.Tests/Rijndael256.Tests.csproj